server:
  port: 8081
spring:
  application:
    name: "Solicitudes"
  devtools:
    add-properties: false
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{X-FLOW-ID:-}] %logger{10} - %msg%n"
  profiles:
    include: null
  level:
    org.springframework.boot.autoconfigure.security: WARN
  r2dbc:
    url: "r2dbc:postgresql://${adapters.r2dbc.postgresql.host}:${adapters.r2dbc.postgresql.port}/${adapters.r2dbc.postgresql.database}"
    username: "${adapters.r2dbc.postgresql.username}"
    password: "${adapters.r2dbc.postgresql.password}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,info"
  endpoint:
    health:
      probes:
        enabled: true
adapters:
  r2dbc:
    postgresql:
      host: "${DB_HOST:localhost}"
      port: "${DB_PORT:5432}"
      database: "${DB_NAME:solicitudes}"
      schema: "${DB_SCHEMA:public}"
      username: "${DB_USER:solicitudes_user}"
      password: "${DB_PASSWORD:pass_solicitudes}"
      initial-size: "${DB_POOL_INITIAL_SIZE:5}"
      max-size: "${DB_POOL_MAX_SIZE:10}"
      max-idle-time-minutes: "${DB_POOL_MAX_IDLE:30}"
app:
  user-service:
    url: "${USER_SERVICE_URL:http://localhost:8080}"
  jwt:
    secret: "crediya-jwt-secret-key-change-in-production-environment-with-minimum-256-bits-for-security"

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"
